
# Generated by Django 3.0.6 on 2020-05-17 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='uploads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userDoc',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('userPhoto', models.CharField(blank=True, max_length=250, null=True)),
                ('userNationalCardPhoto', models.CharField(blank=True, max_length=250, null=True)),
                ('userIdCardPhoto', models.CharField(blank=True, max_length=250, null=True)),
                ('user_pNum', models.CharField(max_length=11, null=True)),
                ('home_pNum', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('zipCode', models.CharField(max_length=10, null=True)),
                ('personalCode', models.CharField(max_length=10, null=True)),
                ('nationalCode', models.CharField(max_length=10, null=True, unique=True)),
                ('father_nationalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=40, null=True)),
                ('father_pNum', models.CharField(blank=True, max_length=11, null=True)),
                ('father_jobName', models.CharField(blank=True, max_length=50, null=True)),
                ('father_jobAddress', models.CharField(blank=True, max_length=250, null=True)),
                ('father_job_pNum', models.CharField(blank=True, max_length=11, null=True)),
                ('father_job_postalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_nationalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=40, null=True)),
                ('mother_pNum', models.CharField(blank=True, max_length=11, null=True)),
                ('mother_jobName', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_jobAddress', models.CharField(blank=True, max_length=250, null=True)),
                ('mother_job_pNum', models.CharField(blank=True, max_length=11, null=True)),
                ('mother_job_postalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('citizen_Num', models.CharField(blank=True, max_length=11, null=True)),
                ('date_of_birth', models.CharField(max_length=50, null=True)),
                ('place_of_birth', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(choices=[('1', 'مدیر'), ('2', 'معاون'), ('3', 'معلم'), ('4', 'دانش آموز')], default='4', max_length=1)),
                ('citizen', models.CharField(choices=[('1', 'اتباع ایرانی'), ('0', 'اتباع خارجی')], default='1', max_length=1)),
                ('gender', models.CharField(choices=[('1', 'آقا'), ('0', 'خانوم')], default='1', max_length=1)),
                ('section', models.CharField(choices=[('0', 'پیش دبستانی'), ('1', 'اول ابتدایی'), ('2', 'دوم ابتدایی'), ('3', 'سوم ابتدایی'), ('4', 'چهارم ابتدایی'), ('5', 'پنجم ابتدایی'), ('6', 'ششم'), ('7', 'هفتم'), ('8', 'هشتم'), ('9', 'نهم'), ('10', 'پرسنل')], default='10', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'personalCode')},
            },

        ),
    ]
