# Generated by Django 3.0.6 on 2020-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='reset_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
