# Generated by Django 3.0.6 on 2020-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gneder',
            field=models.CharField(choices=[('1', 'آقا'), ('0', 'خانوم')], default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationalCode',
            field=models.CharField(default='xxxxxxxxxx', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('1', 'مدیر'), ('2', 'معاون'), ('3', 'معلم'), ('4', 'دانش آموز')], default='4', max_length=4),
        ),
    ]
