# Generated by Django 3.0.6 on 2020-05-20 16:19

from django.conf import settings
from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads', validators=[school.validators.validate_image_size]),
        ),
        migrations.AlterUniqueTogether(
            name='userdoc',
            unique_together={('user', 'nationalCode')},
        ),
    ]
