# Generated by Django 3.0.6 on 2020-05-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nationalCode',
        ),
        migrations.AddField(
            model_name='userdoc',
            name='citizen',
            field=models.CharField(choices=[('1', 'اتباع ایرانی'), ('0', 'اتباع خارجی')], default='1', max_length=40),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='citizen_Num',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='father_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='father_pNum',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='mother_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='nationalCode',
            field=models.IntegerField(null=True),
        ),
    ]
