# Generated by Django 3.0.6 on 2020-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200510_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdoc',
            name='photo',
        ),
        migrations.AddField(
            model_name='userdoc',
            name='father_nationalCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='nationalCardPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='userPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
    ]
