# Generated by Django 3.0.6 on 2020-05-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200510_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gneder',
            new_name='gender',
        ),
    ]
