# Generated by Django 3.0.6 on 2020-05-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='place_of_birth',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
