# Generated by Django 3.0.6 on 2020-05-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200512_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoc',
            name='citizen',
            field=models.IntegerField(choices=[('1', 'اتباع ایرانی'), ('0', 'اتباع خارجی')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='gender',
            field=models.IntegerField(choices=[('1', 'آقا'), ('0', 'خانوم')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='section',
            field=models.IntegerField(choices=[('0', 'پیش دبستانی'), ('1', 'اول ابتدایی'), ('2', 'دوم ابتدایی'), ('3', 'سوم ابتدایی'), ('4', 'چهارم ابتدایی'), ('5', 'پنجم ابتدایی')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[('1', 'مدیر'), ('2', 'معاون'), ('3', 'معلم'), ('4', 'دانش آموز')], default='4', max_length=4),
        ),
    ]
