# Generated by Django 3.0.6 on 2020-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200513_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoc',
            name='father_nationalCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='nationalCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='personalCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='zipCode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
