# Generated by Django 3.0.6 on 2020-05-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20200514_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='father_jobName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='mother_jobName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
