# Generated by Django 3.0.6 on 2020-05-14 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0010_auto_20200514_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoc',
            name='nationalCode',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userdoc',
            unique_together={('user', 'personalCode')},
        ),
    ]
