# Generated by Django 3.0.6 on 2020-05-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20200516_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdoc',
            name='nationalCardPhoto',
        ),
        migrations.AddField(
            model_name='userdoc',
            name='userIdCardPhoto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='userNationalCardPhoto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='userPhoto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
