# Generated by Django 3.0.6 on 2020-05-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20200516_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
