# Generated by Django 3.0.6 on 2020-05-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20200516_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='religon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='date_of_birth',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
