# Generated by Django 3.0.6 on 2020-05-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_auto_20200517_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdoc',
            name='father_job_postalCode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdoc',
            name='mother_job_postalCode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
