# Generated by Django 3.0.6 on 2020-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, null=True)),
                ('content', models.CharField(max_length=20, null=True)),
                ('news_pic', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
