# Generated by Django 3.0.6 on 2020-05-17 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, null=True, unique=True)),
                ('content', models.CharField(max_length=200, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'title')},
            },
        ),
    ]
