# Generated by Django 3.0.6 on 2020-05-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='release_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
