# Generated by Django 3.0.6 on 2020-05-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20200511_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
