# Generated by Django 3.0.6 on 2020-05-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_pic',
            new_name='pic',
        ),
    ]
