# Generated by Django 3.0.6 on 2020-05-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20200514_1931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('id', 'title')},
        ),
    ]
