# Generated by Django 3.0.6 on 2020-05-31 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userclass',
            name='userClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.Classes'),
        ),
        migrations.AlterUniqueTogether(
            name='userclass',
            unique_together={('user', 'userClass')},
        ),
    ]
