# Generated by Django 3.0.6 on 2020-05-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='userClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.Classes', unique=True),
        ),
    ]
