# Generated by Django 3.0.6 on 2020-05-20 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('user', 'name')},
        ),
    ]
