# Generated by Django 3.0.6 on 2020-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='section_id',
            field=models.CharField(choices=[('0', 'پیش دبستانی'), ('1', 'اول ابتدایی'), ('2', 'دوم ابتدایی'), ('3', 'سوم ابتدایی'), ('4', 'چهارم ابتدایی'), ('5', 'پنجم ابتدایی'), ('6', 'ششم'), ('7', 'هفتم'), ('8', 'هشتم'), ('9', 'نهم'), ('10', 'پرسنل')], default='0', max_length=2),
        ),
    ]
