# Generated by Django 3.0.6 on 2020-05-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classes', '0002_auto_20200520_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classes',
            name='user',
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.Classes')),
            ],
            options={
                'unique_together': {('user', 'userClass')},
            },
        ),
    ]
