# Generated by Django 3.0.6 on 2020-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_classes_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
