# Generated by Django 3.0.6 on 2020-07-11 15:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classes', '0004_auto_20200711_1515'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userclass',
            unique_together={('user_id', 'class_id')},
        ),
    ]
