# Generated by Django 3.0.6 on 2020-05-31 08:59

from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='uploads', validators=[school.validators.validate_file_size, school.validators.validate_format_file])),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('release_date', models.CharField(max_length=100, null=True)),
                ('tfile', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
