# Generated by Django 3.0.6 on 2020-05-24 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import school.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutrial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, null=True)),
                ('content', models.CharField(max_length=250, null=True)),
                ('ttype', models.CharField(choices=[('0', 'پست شخصی'), ('1', 'عمومی')], default='1', max_length=1)),
                ('tfile', models.CharField(blank=True, max_length=250, null=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='uploads', validators=[school.validators.validate_file_size, school.validators.format_file])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
