# Generated by Django 3.0.6 on 2020-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tfile',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='ttype',
            field=models.CharField(choices=[('0', 'خصوصی'), ('1', 'عمومی')], default='1', max_length=1),
        ),
    ]
