# Generated by Django 3.0.6 on 2020-05-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutrial',
            name='tfile',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
