# Generated by Django 3.0.6 on 2020-07-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
        ('ClassActivity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_day', models.CharField(choices=[('1', 'شنبه'), ('2', 'یک شنبه'), ('3', 'دو شنبه'), ('4', 'سه شنبه'), ('5', 'چهار شنبه'), ('6', 'پنج شنبه')], default='1', max_length=1)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classes.Classes')),
                ('fifth_bell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_bell', to='ClassActivity.Lessons')),
                ('first_bell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_bell', to='ClassActivity.Lessons')),
                ('forth_bell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forth_bell', to='ClassActivity.Lessons')),
                ('second_bell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_bell', to='ClassActivity.Lessons')),
                ('third_bell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_bell', to='ClassActivity.Lessons')),
            ],
        ),
    ]
