# Generated by Django 3.0.6 on 2020-07-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassActivity', '0004_presentabsentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='week_day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنبه'), ('3', 'سه شنبه'), ('4', 'چهار شنبه'), ('5', 'پنج شنبه'), ('6', 'جمعه')], default='0', max_length=1),
        ),
    ]
