# Generated by Django 3.0.6 on 2020-07-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassActivity', '0005_auto_20200711_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
