# Generated by Django 3.0.6 on 2020-07-14 04:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassActivity', '0008_gradelist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presentabsentlist',
            unique_together={('user_id', 'day', 'month', 'year')},
        ),
    ]
