# Generated by Django 3.0.6 on 2020-07-14 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassActivity', '0009_auto_20200714_0428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresentAbsentList',
            new_name='AttendanceList',
        ),
    ]
