# Generated by Django 3.0.6 on 2020-07-14 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassActivity', '0010_auto_20200714_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradelist',
            unique_together={('grade_owner_id', 'day', 'month', 'year')},
        ),
    ]
