# Generated by Django 3.0.6 on 2020-07-14 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassActivity', '0011_auto_20200714_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradelist',
            unique_together={('grade_owner_id', 'day', 'month', 'year', 'lesson_id')},
        ),
    ]
