# Generated by Django 3.0.6 on 2020-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassActivity', '0012_auto_20200714_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelist',
            name='excused',
            field=models.CharField(choices=[('0', 'حاضر'), ('1', 'غیبت موجه')], default='0', max_length=1),
        ),
    ]
